name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure git
        run: |
          git config --global user.email "builds@github-actions.com"
          git config --global user.name "GitHub Actions"

      - name: Install dependencies
        run: npm install --legacy-peer-deps --ignore-scripts

      - name: Build
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        run: npm run build

      - name: Bump version
        run: |
          npm version patch -m "[CHORE] Bump Version %s [skip ci]"
          git push origin master
          git push origin --tags

      - name: Deploy to Firebase Hosting
        run: npx firebase-tools deploy --token ${{ secrets.FIREBASE_TOKEN }} --non-interactive
